#!/bin/bash

if [ -z "$1" ]; then

	echo "Usage `basename "$0"` CONTAINER [COMMAND [ARG]...]"
	echo ""
	echo "Enters the Docker CONTAINER and executes the specified COMMAND."
	echo "If COMMAND is not specified, runs an interactive shell in CONTAINER."
	exit 1

fi


NSENTER=`which nsenter 2> /dev/null`

if [ -z "$NSENTER" ]; then

	echo "WARN Cannot find nsenter"
	exit 2
else

	NSENTER=`which nsenter`

fi



PID=`docker inspect --format '{{.State.Pid}}' $1 2> /dev/null`
if [ -z "$PID" ]; then

	echo "WARN Connot find the given container"

else

	$NSENTER --target $PID --mount --uts --ipc --net --pid

fi




